version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: adventskalender-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SITE_PASSWORD=${SITE_PASSWORD}
      - ADVENT_START_DATE=${ADVENT_START_DATE}
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - MAX_FILE_SIZE=52428800
      - THUMBNAIL_WIDTH=500
      - THUMBNAIL_QUALITY=85
    volumes:
      - ./backend/media:/app/media
      - ./backend/thumbnails:/app/thumbnails
      - ./backend/messages:/app/messages
      - ./backend/polls:/app/polls
      - ./backend/assets:/app/assets
    restart: unless-stopped
    depends_on:
      - nginx-backend

  frontend:
    build:
      context: ./frontend/adventskalender
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: adventskalender-frontend
    restart: unless-stopped
    depends_on:
      - nginx-frontend

  nginx-backend:
    image: nginx:alpine
    container_name: nginx-backend
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/nginx/allowed_ips.conf:/etc/nginx/allowed_ips.conf:ro
    ports:
      - "5000:80"
    restart: unless-stopped

  nginx-frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    volumes:
      - ./frontend/adventskalender/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/adventskalender/nginx/allowed_ips.conf:/etc/nginx/allowed_ips.conf:ro
    ports:
      - "3000:80"
    restart: unless-stopped