services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: adventskalender-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SITE_PASSWORD=${SITE_PASSWORD}
      - ADVENT_START_DATE=${ADVENT_START_DATE}
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - MAX_FILE_SIZE=52428800
      - THUMBNAIL_WIDTH=500
      - THUMBNAIL_QUALITY=85
    volumes:
      - ./backend/media:/app/media
      - ./backend/thumbnails:/app/thumbnails
      - ./backend/messages:/app/messages
      - ./backend/polls:/app/polls
      - ./backend/assets:/app/assets
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/adventskalender
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    container_name: adventskalender-frontend
    restart: unless-stopped

  nginx-backend:
    image: nginx:alpine
    container_name: nginx-backend
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"  # Geändert von 80 auf 8080
    depends_on:
      - backend
    restart: unless-stopped

  nginx-frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    volumes:
      - ./frontend/adventskalender/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/adventskalender/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/adventskalender/build:/usr/share/nginx/html:ro
    ports:
      - "8081:8081"  # Geändert von 80 auf 8081
    depends_on:
      - frontend
    restart: unless-stopped