version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/media:/app/media
      - ./backend/thumbnails:/app/thumbnails
      - ./backend/messages:/app/messages
      - ./backend/polls:/app/polls
      - ./backend/assets:/app/assets
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SITE_PASSWORD=${SITE_PASSWORD}
      - ADVENT_START_DATE=${ADVENT_START_DATE}
      - ALLOWED_IPS=${ALLOWED_IPS}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
    networks:
      - advent_network

  frontend:
    build:
      context: ./frontend/adventskalender
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - ALLOWED_IPS=${ALLOWED_IPS}
    depends_on:
      - backend
    networks:
      - advent_network

networks:
  advent_network:
    driver: bridge