services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/media:/app/media
      - ./backend/thumbnails:/app/thumbnails
      - ./backend/messages:/app/messages
      - ./backend/polls:/app/polls
      - ./backend/assets:/app/assets
      - ./backend/nginx:/etc/nginx/conf.d
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SITE_PASSWORD=${SITE_PASSWORD}
      - ADVENT_START_DATE=${ADVENT_START_DATE}
      - ALLOWED_IPS=${ALLOWED_IPS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - THUMBNAIL_WIDTH=${THUMBNAIL_WIDTH}
      - THUMBNAIL_QUALITY=${THUMBNAIL_QUALITY}
      - FFMPEG_PATH=${FFMPEG_PATH}
      - FFPROBE_PATH=${FFPROBE_PATH}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
      - MEDIA_PATH=${MEDIA_PATH}
      - THUMBNAILS_PATH=${THUMBNAILS_PATH}
      - MESSAGES_PATH=${MESSAGES_PATH}
      - POLLS_PATH=${POLLS_PATH}
      - ASSETS_PATH=${ASSETS_PATH}
    networks:
      - advent_network

  frontend:
    build:
      context: ./frontend/adventskalender
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - ALLOWED_IPS=${ALLOWED_IPS}
    depends_on:
      - backend
    networks:
      - advent_network

networks:
  advent_network:
    driver: bridge